name: Update Kaggle Crypto Data Hourly

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes 
  workflow_dispatch:  # âœ… Enables manual trigger
  
permissions:
  contents: write

jobs:
  get_and_upload_crypto_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

    - name: Run update script
      run: |
        python crypto.py

    - name: Update Kaggle Dataset
      env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: kaggle datasets version -p storage -m "Automatic Update"

    - name: Update and commit crypto.py
      run: |
        # Add or update a timestamp comment at top of file
        sed -i "1s|^# Last run:.*|# Last run: $(date -u)|; 1t; 1i # Last run: $(date -u)" crypto.py

        git config --global user.name "adrianjuliusaluoch"
        git config --global user.email "adrianjuliusaluoch@gmail.com"
        git add crypto.py
        git commit -m "Auto update search.py timestamp [skip ci]" || echo "No changes"
        git pull --rebase origin main
        git push
